#!/bin/bash
#
# newrhelic          Start up the NewRHELic Plugin for New Relic Monitoring
#
# chkconfig: 35 99 10
# description: This is a RHEL/CentOS-centric New Relic monitoring plugin
#
# processname: newrhelic
# config: /etc/newrhelic.conf
# pidfile: /var/run/newrhelic.pid

/usr/bin/newrhelic $1

